package web

import (
	"encoding/json"
)

// ProtocolVersion identifies the core<->client wire protocol.
const ProtocolVersion = 1

// Envelope types. Server -> client: hello, snapshot, account_state, batch,
// ack, err. Client -> server: cmd. Request/response reads (history, ads,
// presence search) are HTTP endpoints, not envelopes.
const (
	THello        = "hello"
	TSnapshot     = "snapshot"
	TAccountState = "account_state"
	TBatch        = "batch"
	TAck          = "ack"
	TErr          = "err"
	TCmd          = "cmd"
	TSubscribe    = "subscribe"
)

// Envelope is the single message shape in both directions. Type selects the
// payload in Data; CID correlates a command with its ack/err.
type Envelope struct {
	Type string          `json:"t"`
	CID  string          `json:"cid,omitempty"`
	Data json.RawMessage `json:"d,omitempty"`
}

// Hello is the first server message after a successful subscribe. Resumed
// reports whether the socket reattached to an existing subscription (interest
// preserved) or started a fresh one (client must re-assert interest). Version
// identifies the wire protocol; it is for diagnostics, not negotiation, because
// the UI is embedded in this binary and cannot drift.
type Hello struct {
	Version int  `json:"v"`
	Resumed bool `json:"resumed"`
}

// Subscribe is the first envelope a client sends. It names the durable
// subscription this socket attaches to, so a reconnect with the same id resumes
// the interest this client already asserted instead of restarting at the
// subscription default. The id is generated by the client and stable for the
// lifetime of one Transport (a page reload starts a new one).
type Subscribe struct {
	ID string `json:"id"`
}

func rawJSON(v any) json.RawMessage {
	b, err := json.Marshal(v)
	if err != nil {
		return json.RawMessage(`{}`)
	}
	return b
}
