// Code generated by cmd/tsgen. DO NOT EDIT.
// Source of truth: the const declarations in internal/model, internal/activity,
// and internal/web; run `go generate ./cmd/tsgen` after changing them.

export type AccountStatus = "missing" | "checking" | "ok" | "invalid" | "unreachable";

export type CommandLayer = "account" | "manager" | "session" | "broker";

export type CommandScope = "global" | "session" | "conversation";

export type ConvKind = "official" | "room" | "dm" | "broadcast" | "warp";

export type EnvelopeType = "hello" | "snapshot" | "account_state" | "batch" | "ack" | "err" | "cmd" | "subscribe";

export type EventKind = "message" | "state" | "conv_view" | "error";

export type Interest = "none" | "summary" | "full";

export type LogActivityScope = "conversation" | "self";

export type LogConvKind = "official" | "room" | "dm";

export const OPS = {
	setCredentials: "set_credentials",
	clearCredentials: "clear_credentials",
	purgeCredentials: "purge_credentials",
	listCharacters: "list_characters",
	login: "login",
	logout: "logout",
	reconnect: "reconnect",
	sendMessage: "send_message",
	sendLRP: "send_lrp",
	sendTyping: "send_typing",
	join: "join",
	leave: "leave",
	setStatus: "set_status",
	setIgnore: "set_ignore",
	setBookmark: "set_bookmark",
	setTracked: "set_tracked",
	roomAdmin: "room_admin",
	dismissInvite: "dismiss_invite",
	setInterest: "set_interest",
} as const;

export type Op = (typeof OPS)[keyof typeof OPS];

export type RoomRole = "none" | "mod" | "owner";

export type SearchIDType = "number" | "string";

export type SessionState = "connecting" | "live" | "disconnected";

export type Severity = "normal" | "severe";

export type StateNamespace = "account" | "session" | "conv" | "summary" | "typing" | "character" | "search" | "invites";

