// Code generated by cmd/tsgen. DO NOT EDIT.
// Source of truth: internal/model, internal/activity, and internal/web; run `go generate ./cmd/tsgen` after changing them.
//
// JSON numbers are TypeScript numbers (int64 included): the wire is JSON and
// JSON.parse yields doubles, so a bigint would not describe what arrives.

import type { ConvKind, LogActivityScope, LogConvKind, RoomRole, SearchIDType, SessionState, Severity } from "./enums.js";

export interface Ad {
	character: string;
	channel: string;
	message: string;
	receivedAt: string;
}

export interface AdBody {
	name: string;
	body: string;
}

export interface AdCampaign {
	enabled: boolean;
	ads?: AdBody[];
	channels?: AdChannel[];
}

export interface AdChannel {
	kind: ConvKind;
	id: string;
	name?: string;
	ads?: string[];
}

export interface AdTargetStatus {
	kind: ConvKind;
	id: string;
	name?: string;
	ads?: string[];
	state: string;
	reason?: string;
	nextEligibleAt?: string;
	lastBody?: string;
	lastError?: string;
}

export interface AdsCampaignView {
	campaign?: AdCampaign;
	status: AdsStatus;
	running: boolean;
	available?: AdChannel[];
}

export interface AdsStatus {
	running: boolean;
	enabled: boolean;
	targets?: AdTargetStatus[];
}

export interface Batch {
	events: Event[];
}

export interface ChannelsPayload {
	official: OfficialChannelInfo[];
	rooms: PublicRoomInfo[];
}

export interface ConvRef {
	kind: ConvKind;
	id: string;
}

export interface ConvStatePayload {
	title?: string;
	description?: string;
	mode?: string;
	members?: string[];
	ops: string[];
	role?: RoomRole;
}

export interface ConvSummary {
	conv: ConvRef;
	kind: ConvKind;
	title?: string;
	lastActivity: string;
	role?: RoomRole;
}

export interface ConvView {
	session: string;
	conv: ConvRef;
	title?: string;
	description?: string;
	mode?: string;
	members?: MemberInfo[];
	ops?: string[];
	window: Entry[];
	cursor: Cursor;
	delta?: boolean;
	role?: RoomRole;
}

export interface Cursor {
	asOfSeq: number;
	oldestSeq: number;
	hasOlder: boolean;
}

export interface Entry {
	id: string;
	convSeq: number;
	kind: string;
	speaker: string;
	createdAtMs: number;
	html: string;
}

export interface ErrorPayload {
	session?: string;
	code?: number;
	message?: string;
}

export interface FriendsPayload {
	friends: MemberInfo[];
	bookmarks: MemberInfo[];
}

export interface Hello {
	v: number;
	resumed: boolean;
}

export interface History {
	session: string;
	conv: ConvRef;
	entries: Entry[];
}

export interface IgnoresPayload {
	ignores: string[];
}

export interface InvitesPayload {
	invites: RoomInvite[];
}

export interface LogActivityBucket {
	startMs: number;
	count: number;
}

export interface LogActivityDetail {
	scope: LogActivityScope;
	sessions: LogSession[];
	summary: LogSession;
}

export interface LogActivityOverview {
	scope: LogActivityScope;
	unitMs: number;
	total: number;
	buckets: LogActivityBucket[];
	participation?: LogParticipation;
}

export interface LogCleanupRequest {
	op: "age" | "conversation" | "dms";
	session?: string;
	kind?: LogConvKind;
	id?: string;
	days?: number;
	maxEntries?: number;
	apply: boolean;
}

export interface LogCleanupResult {
	conversations: number;
	entries: number;
	warpmarks: number;
	bodyBytes: number;
	vacuumed: boolean;
	bytesReclaimed: number;
}

export interface LogConvRef {
	kind: LogConvKind;
	id: string;
	name: string;
}

export interface LogCoverage {
	count: number;
	firstMs: number;
	lastMs: number;
	firstSeq: number;
	lastSeq: number;
	name: string;
}

export interface LogParticipation {
	sampled: number;
	active: number;
	effective: number;
}

export interface LogSession {
	startMs: number;
	endMs: number;
	count: number;
	volume: number;
	longCount: number;
	activeMs: number;
	rp: boolean;
}

export interface LogSessionConv {
	session: string;
	kind: LogConvKind;
	id: string;
	name: string;
}

export interface MemberInfo {
	name: string;
	gender?: string;
	status?: string;
	statusMsg?: string;
	admin: boolean;
	online: boolean;
}

export interface MessagePayload {
	session: string;
	conv: ConvRef;
	entry: Entry;
	self: boolean;
	highlight?: boolean;
	cid?: string;
}

export interface OfficialChannelInfo {
	name: string;
	characters: number;
}

export interface PresencePayload {
	character: string;
	gender?: string;
	status?: string;
	statusMsg?: string;
	admin: boolean;
	online: boolean;
}

export interface PublicRoomInfo {
	name: string;
	title: string;
	characters: number;
}

export interface RenderRequest {
	bbcode: string;
}

export interface RenderResponse {
	html: string;
}

export interface Result {
	cid: string;
	accepted: boolean;
	errorCode?: string;
	errorMsg?: string;
}

export interface RoomAdminRequest {
	action: string;
	character?: string;
	title?: string;
	description?: string;
	mode?: string;
	visibility?: string;
	length?: number;
}

export interface RoomBan {
	name: string;
	banner?: string;
	expiresAtMs?: number;
}

export interface RoomInfo {
	conv: ConvRef;
	title?: string;
	description?: string;
	rawDescription?: string;
	mode?: string;
	owner?: string;
	ops: string[];
	selfRole: RoomRole;
	bans: RoomBan[];
	cdsMax?: number;
	titleMax?: number;
	visibility?: string;
}

export interface RoomInvite {
	conv: ConvRef;
	title?: string;
	invitedBy?: string;
}

export interface SearchEntry {
	name: string;
	id: string | number;
}

export interface SearchField {
	name: string;
	field: string;
	idtype: SearchIDType;
	entries: SearchEntry[];
}

export type SearchMapping = Record<string, SearchField>;

export interface SearchNotice {
	revision: number;
}

export interface SearchPayload {
	characters: MemberInfo[];
	revision: number;
}

export interface SearchQuery {
	kinks: number[];
	genders?: string[];
	orientations?: string[];
	languages?: string[];
	furryprefs?: string[];
	roles?: string[];
}

export interface SessionSnapshot {
	character: string;
	state: SessionState;
	reason?: string;
	severity?: Severity;
	autoRetry?: boolean;
	self: PresencePayload;
	selfStatusText?: string;
	adCount: number;
	chatMax?: number;
	privMax?: number;
	conversations: ConvSummary[];
	invites: RoomInvite[];
}

export interface SessionStatePayload {
	state: SessionState;
	reason?: string;
	severity?: Severity;
	autoRetry?: boolean;
}

export interface Snapshot {
	sessions: SessionSnapshot[];
	friends?: MemberInfo[];
	bookmarks?: MemberInfo[];
	ignores?: string[];
	catalog: ChannelsPayload;
}

export interface StatePayload {
	key: string;
	value?: unknown;
	removed?: boolean;
}

export interface Subscribe {
	id: string;
}

export interface SummaryPayload {
	title?: string;
	self?: boolean;
	highlight?: boolean;
	lastActivity: string;
}

export interface TypingPayload {
	on: boolean;
	paused?: boolean;
}

export interface Warpmark {
	session: string;
	entryId: string;
	label: string;
	conv: ConvRef;
	convName?: string;
	speaker: string;
	createdAt: string;
	convSeq?: number;
	html?: string;
	missing?: boolean;
}

export type Event =
	| { kind: "message"; payload: MessagePayload }
	| { kind: "state"; payload: StatePayload }
	| { kind: "conv_view"; payload: ConvView }
	| { kind: "error"; payload: ErrorPayload };
