package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

// enumSourceFiles are the Go files cmd/tsgen reads for string constants. The
// const declarations are the source of truth for the generated unions; the
// struct shapes are reflected separately. Parsing the const blocks (rather than
// re-listing the values) is what keeps the client unions honest.
var enumSourceFiles = []string{
	"../../internal/model/model.go",
	"../../internal/model/commands.go",
	"../../internal/model/account.go",
	"../../internal/activity/activity.go",
	"../../internal/web/protocol.go",
}

// constGroup lifts a run of untyped string constants sharing a name prefix into
// a TypeScript union. Members must be declared without an explicit type; a
// typed Go const is discovered automatically instead.
type constGroup struct {
	Prefix string
	TSName string
}

var constGroups = []constGroup{
	{Prefix: "T", TSName: "EnvelopeType"},
	{Prefix: "State", TSName: "StateNamespace"},
	{Prefix: "Account", TSName: "AccountStatus"},
	{Prefix: "SearchID", TSName: "SearchIDType"},
	{Prefix: "LogConv", TSName: "LogConvKind"},
}

// objectEnums maps a typed Go enum to a TypeScript const object. The union is
// derived from the object (`(typeof X)[keyof typeof X]`), so the value list and
// the object cannot drift apart. Keys are the Go const name minus its type
// prefix, lower-cased on the first rune.
var objectEnums = map[string]string{"Op": "OPS"}

// enumDef is one generated TypeScript union.
type enumDef struct {
	GoName string // the typed const's Go type, empty for an untyped group
	TSName string
	Object string // non-empty emits a const object and derives the union
	Names  []string
	Values []string
}

// parseEnums reads every string const in enumSourceFiles and returns the
// unions to generate: one per typed Go string type, plus the configured
// untyped groups.
func parseEnums() ([]enumDef, error) {
	typed := map[string]*enumDef{}
	var typedOrder []string
	type namedConst struct{ name, value string }
	var untyped []namedConst

	for _, path := range enumSourceFiles {
		fset := token.NewFileSet()
		f, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", path, err)
		}
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.CONST {
				continue
			}
			current := ""
			for _, spec := range gd.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}
				if vs.Type != nil {
					if id, ok := vs.Type.(*ast.Ident); ok {
						current = id.Name
					} else {
						current = ""
					}
				}
				for i, v := range vs.Values {
					lit, ok := v.(*ast.BasicLit)
					if !ok || lit.Kind != token.STRING {
						continue
					}
					val, err := strconv.Unquote(lit.Value)
					if err != nil {
						return nil, fmt.Errorf("%s: %w", path, err)
					}
					name := ""
					if i < len(vs.Names) {
						name = vs.Names[i].Name
					}
					if current != "" {
						e := typed[current]
						if e == nil {
							e = &enumDef{GoName: current, TSName: tsName(current)}
							typed[current] = e
							typedOrder = append(typedOrder, current)
						}
						e.Names = append(e.Names, name)
						e.Values = append(e.Values, val)
					} else if name != "" {
						untyped = append(untyped, namedConst{name, val})
					}
				}
			}
		}
	}

	out := make([]enumDef, 0, len(typedOrder)+len(constGroups))
	for _, goName := range typedOrder {
		e := *typed[goName]
		e.Object = objectEnums[goName]
		out = append(out, e)
	}
	for _, g := range constGroups {
		var names, values []string
		for _, u := range untyped {
			if strings.HasPrefix(u.name, g.Prefix) {
				names = append(names, u.name)
				values = append(values, u.value)
			}
		}
		if len(values) == 0 {
			continue
		}
		out = append(out, enumDef{TSName: g.TSName, Names: names, Values: values})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].TSName < out[j].TSName })
	return out, nil
}

// GenerateEnums renders ui/src/transport/enums.ts.
func GenerateEnums() ([]byte, error) {
	defs, err := parseEnums()
	if err != nil {
		return nil, err
	}
	var b strings.Builder
	b.WriteString("// Code generated by cmd/tsgen. DO NOT EDIT.\n")
	b.WriteString("// Source of truth: the const declarations in internal/model, internal/activity,\n")
	b.WriteString("// and internal/web; run `go generate ./cmd/tsgen` after changing them.\n\n")
	for _, e := range defs {
		if e.Object != "" {
			fmt.Fprintf(&b, "export const %s = {\n", e.Object)
			for i, v := range e.Values {
				fmt.Fprintf(&b, "\t%s: %q,\n", objectKey(e.GoName, e.Names[i]), v)
			}
			fmt.Fprintf(&b, "} as const;\n\n")
			fmt.Fprintf(&b, "export type %s = (typeof %s)[keyof typeof %s];\n\n", e.TSName, e.Object, e.Object)
			continue
		}
		parts := make([]string, len(e.Values))
		for i, v := range e.Values {
			parts[i] = strconv.Quote(v)
		}
		fmt.Fprintf(&b, "export type %s = %s;\n\n", e.TSName, strings.Join(parts, " | "))
	}
	return []byte(b.String()), nil
}

// objectKey derives a const-object key from a Go const name: "OpSetCredentials"
// (prefix "Op") becomes "setCredentials".
func objectKey(prefix, name string) string {
	return lowerFirst(strings.TrimPrefix(name, prefix))
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	r, size := utf8.DecodeRuneInString(s)
	return string(unicode.ToLower(r)) + s[size:]
}
